version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_broker
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - backend

  kafka-connect:
    image: debezium/connect:2.7.3.Final
    environment:
      - GROUP_ID="1"
      - CONFIG_STORAGE_TOPIC="docker-connect-configs"
      - OFFSET_STORAGE_TOPIC="docker-connect-offsets"
      - STATUS_STORAGE_TOPIC="docker-connect-status"
      - BOOTSTRAP_SERVERS=165.232.185.65:9092
    ports:
      - "8083:8083"
    networks:
      - backend
  
  consumer:
    build: ./consumer
    container_name: kafka_consumer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=165.232.185.65:9092
      - MIXTRAL_API_URL=https://api.mistral.ai/v1/chat/completions
    networks:
      - backend

networks:
  backend:
    driver: bridge
